export const tableData = [
  {
    id: "0001",
    title: "OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO",
    department: "IT",
    owner: "小明",
    submitDate: "2024-12-01",
    status: "pending",
  },
  {
    id: "0002",
    title: "OOOOOOOOOOOOO",
    department: "HR",
    owner: "小紅",
    submitDate: "2024-12-02",
    status: "closed",
  },
  {
    id: "0003",
    title: "OOOOOOOOOOOOOOOOOOOOOO",
    department: "財務",
    owner: "小王",
    submitDate: "2024-12-03",
    status: "reviewing",
  },
  {
    id: "0004",
    title: "OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO",
    department: "IT",
    owner: "小明",
    submitDate: "2024-12-04",
    status: "closed",
  },
  {
    id: "0005",
    title: "OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO",
    department: "行銷",
    owner: "小李",
    submitDate: "2024-12-05",
    status: "pending",
  },
  {
    id: "0006",
    title: "OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO",
    department: "財務",
    owner: "小王",
    submitDate: "2024-12-06",
    status: "recheck",
  },
  {
    id: "0007",
    title: "OOOOOOOOOOO",
    department: "行銷",
    owner: "小李",
    submitDate: "2024-12-07",
    status: "recheck",
  },
  {
    id: "0008",
    title: "OOOOOOOO",
    department: "HR",
    owner: "小紅",
    submitDate: "2024-12-08",
    status: "closed",
  },
  {
    id: "0009",
    title: "OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO",
    department: "行銷",
    owner: "小李",
    submitDate: "2024-12-09",
    status: "pending",
  },
  {
    id: "0010",
    title: "OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO",
    department: "IT",
    owner: "小明",
    submitDate: "2024-12-10",
    status: "closed",
  },
  {
    id: "0011",
    title: "OOOOO",
    department: "財務",
    owner: "小王",
    submitDate: "2024-12-11",
    status: "pending",
  },
  {
    id: "0012",
    title: "OOOOOOOOOOOO",
    department: "行銷",
    owner: "小李",
    submitDate: "2024-12-12",
    status: "closed",
  },
  {
    id: "0013",
    title: "OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO",
    department: "IT",
    owner: "小明",
    submitDate: "2024-12-01",
    status: "pending",
  },
  {
    id: "0014",
    title: "OOOOOOOOOOOOO",
    department: "HR",
    owner: "小紅",
    submitDate: "2024-12-02",
    status: "closed",
  },
  {
    id: "0015",
    title: "OOOOOOOOOOOOOOOOOOOOOO",
    department: "財務",
    owner: "小王",
    submitDate: "2024-12-03",
    status: "reviewing",
  },
  {
    id: "0016",
    title: "OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO",
    department: "IT",
    owner: "小明",
    submitDate: "2024-12-04",
    status: "closed",
  },
  {
    id: "0017",
    title: "OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO",
    department: "行銷",
    owner: "小李",
    submitDate: "2024-12-05",
    status: "pending",
  },
  {
    id: "0018",
    title: "OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO",
    department: "財務",
    owner: "小王",
    submitDate: "2024-12-06",
    status: "recheck",
  },
  {
    id: "0019",
    title: "OOOOOOOOOOO",
    department: "行銷",
    owner: "小李",
    submitDate: "2024-12-07",
    status: "recheck",
  },
  {
    id: "0020",
    title: "OOOOOOOO",
    department: "HR",
    owner: "小紅",
    submitDate: "2024-12-08",
    status: "closed",
  },
  {
    id: "0021",
    title: "OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO",
    department: "行銷",
    owner: "小李",
    submitDate: "2024-12-09",
    status: "pending",
  },
  {
    id: "0022",
    title: "OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO",
    department: "IT",
    owner: "小明",
    submitDate: "2024-12-10",
    status: "closed",
  },
  {
    id: "0023",
    title: "OOOOO",
    department: "財務",
    owner: "小王",
    submitDate: "2024-12-11",
    status: "pending",
  },
  {
    id: "0024",
    title: "OOOOOOOOOOOO",
    department: "行銷",
    owner: "小李",
    submitDate: "2024-12-12",
    status: "closed",
  },
  {
    id: "0025",
    title: "OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO",
    department: "行銷",
    owner: "小李",
    submitDate: "2024-12-09",
    status: "pending",
  },
  {
    id: "0026",
    title: "OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO",
    department: "IT",
    owner: "小明",
    submitDate: "2024-12-10",
    status: "closed",
  },
  {
    id: "0027",
    title: "OOOOO",
    department: "財務",
    owner: "小王",
    submitDate: "2024-12-11",
    status: "pending",
  },
  {
    id: "0028",
    title: "OOOOOOOOOOOO",
    department: "行銷",
    owner: "小李",
    submitDate: "2024-12-12",
    status: "closed",
  },
  {
    id: "0029",
    title: "OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO",
    department: "IT",
    owner: "小明",
    submitDate: "2024-12-04",
    status: "closed",
  },
  {
    id: "0030",
    title: "OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO",
    department: "行銷",
    owner: "小李",
    submitDate: "2024-12-05",
    status: "pending",
  },
  {
    id: "0031",
    title: "OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO",
    department: "行銷",
    owner: "小李",
    submitDate: "2024-12-09",
    status: "pending",
  },
  {
    id: "0032",
    title: "OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO",
    department: "IT",
    owner: "小明",
    submitDate: "2024-12-10",
    status: "closed",
  },
  {
    id: "0033",
    title: "OOOOO",
    department: "財務",
    owner: "小王",
    submitDate: "2024-12-11",
    status: "pending",
  },
  {
    id: "0034",
    title: "OOOOOOOOOOOO",
    department: "行銷",
    owner: "小李",
    submitDate: "2024-12-12",
    status: "closed",
  },
  {
    id: "0035",
    title: "OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO",
    department: "行銷",
    owner: "小李",
    submitDate: "2024-12-09",
    status: "pending",
  },
];
