export const tableData = [
  {
    id: "0001",
    title: "OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO",
    department: "IT",
    owner: "小明",
    submitDate: "2024-12-01",
    status: "pending",
  },
  {
    id: "0002",
    title: "OOOOOOOOOOOOO",
    department: "HR",
    owner: "小紅",
    submitDate: "2024-12-02",
    status: "closed",
  },
  {
    id: "0003",
    title: "OOOOOOOOOOOOOOOOOOOOOO",
    department: "財務",
    owner: "小王",
    submitDate: "2024-12-03",
    status: "reviewing",
  },
  {
    id: "0004",
    title: "OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO",
    department: "IT",
    owner: "小明",
    submitDate: "2024-12-04",
    status: "closed",
  },
  {
    id: "0005",
    title: "OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO",
    department: "行銷",
    owner: "小李",
    submitDate: "2024-12-05",
    status: "pending",
  },
  {
    id: "0006",
    title: "OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO",
    department: "財務",
    owner: "小王",
    submitDate: "2024-12-06",
    status: "recheck",
  },
  {
    id: "0007",
    title: "OOOOOOOOOOO",
    department: "行銷",
    owner: "小李",
    submitDate: "2024-12-07",
    status: "recheck",
  },
  {
    id: "0008",
    title: "OOOOOOOO",
    department: "HR",
    owner: "小紅",
    submitDate: "2024-12-08",
    status: "closed",
  },
  {
    id: "0009",
    title: "OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO",
    department: "行銷",
    owner: "小李",
    submitDate: "2024-12-09",
    status: "pending",
  },
  {
    id: "0010",
    title: "OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO",
    department: "IT",
    owner: "小明",
    submitDate: "2024-12-10",
    status: "closed",
  },
  {
    id: "0011",
    title: "OOOOO",
    department: "財務",
    owner: "小王",
    submitDate: "2024-12-11",
    status: "pending",
  },
  {
    id: "0012",
    title: "OOOOOOOOOOOO",
    department: "行銷",
    owner: "小李",
    submitDate: "2024-12-12",
    status: "closed",
  },
  {
    id: "0013",
    title: "OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO",
    department: "IT",
    owner: "小明",
    submitDate: "2024-12-01",
    status: "pending",
  },
  {
    id: "0014",
    title: "OOOOOOOOOOOOO",
    department: "HR",
    owner: "小紅",
    submitDate: "2024-12-02",
    status: "closed",
  },
  {
    id: "0015",
    title: "OOOOOOOOOOOOOOOOOOOOOO",
    department: "財務",
    owner: "小王",
    submitDate: "2024-12-03",
    status: "reviewing",
  },
  {
    id: "0016",
    title: "OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO",
    department: "IT",
    owner: "小明",
    submitDate: "2024-12-04",
    status: "closed",
  },
  {
    id: "0017",
    title: "OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO",
    department: "行銷",
    owner: "小李",
    submitDate: "2024-12-05",
    status: "pending",
  },
  {
    id: "0018",
    title: "OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO",
    department: "財務",
    owner: "小王",
    submitDate: "2024-12-06",
    status: "recheck",
  },
  {
    id: "0019",
    title: "OOOOOOOOOOO",
    department: "行銷",
    owner: "小李",
    submitDate: "2024-12-07",
    status: "recheck",
  },
  {
    id: "0020",
    title: "OOOOOOOO",
    department: "HR",
    owner: "小紅",
    submitDate: "2024-12-08",
    status: "closed",
  },
  {
    id: "0021",
    title: "OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO",
    department: "行銷",
    owner: "小李",
    submitDate: "2024-12-09",
    status: "pending",
  },
  {
    id: "0022",
    title: "OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO",
    department: "IT",
    owner: "小明",
    submitDate: "2024-12-10",
    status: "closed",
  },
  {
    id: "0023",
    title: "OOOOO",
    department: "財務",
    owner: "小王",
    submitDate: "2024-12-11",
    status: "pending",
  },
  {
    id: "0024",
    title: "OOOOOOOOOOOO",
    department: "行銷",
    owner: "小李",
    submitDate: "2024-12-12",
    status: "closed",
  },
  {
    id: "0025",
    title: "OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO",
    department: "行銷",
    owner: "小李",
    submitDate: "2024-12-09",
    status: "pending",
  },
  {
    id: "0026",
    title: "OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO",
    department: "IT",
    owner: "小明",
    submitDate: "2024-12-10",
    status: "closed",
  },
  {
    id: "0027",
    title: "OOOOO",
    department: "財務",
    owner: "小王",
    submitDate: "2024-12-11",
    status: "pending",
  },
  {
    id: "0028",
    title: "OOOOOOOOOOOO",
    department: "行銷",
    owner: "小李",
    submitDate: "2024-12-12",
    status: "closed",
  },
  {
    id: "0029",
    title: "OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO",
    department: "IT",
    owner: "小明",
    submitDate: "2024-12-04",
    status: "closed",
  },
  {
    id: "0030",
    title: "OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO",
    department: "行銷",
    owner: "小李",
    submitDate: "2024-12-05",
    status: "pending",
  },
  {
    id: "0031",
    title: "OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO",
    department: "行銷",
    owner: "小李",
    submitDate: "2024-12-09",
    status: "pending",
  },
  {
    id: "0032",
    title: "OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO",
    department: "IT",
    owner: "小明",
    submitDate: "2024-12-10",
    status: "closed",
  },
  {
    id: "0033",
    title: "OOOOO",
    department: "財務",
    owner: "小王",
    submitDate: "2024-12-11",
    status: "pending",
  },
  {
    id: "0034",
    title: "OOOOOOOOOOOO",
    department: "行銷",
    owner: "小李",
    submitDate: "2024-12-12",
    status: "closed",
  },
  {
    id: "0035",
    title: "OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO",
    department: "行銷",
    owner: "小李",
    submitDate: "2024-12-09",
    status: "pending",
  },
];

export const newsData = [
  {
    id: 1,
    title: "政府資安人力職能轉換訓練(本訓練不須會員資格)",
    type: "event",
    date: "2024-12-01",
  },
  {
    id: 2,
    title: "最新消息內文最新消息內文最新消息內文最新消息內文",
    type: "news",
    date: "2024-11-28",
  },
  {
    id: 3,
    title:
      "最新消息內文最新消息內文最新消息內文最新消息內文最新消息內文最新消息內文最新消息內文最新消息內文",
    type: "announcement",
    date: "2024-11-26",
  },
  {
    id: 4,
    title:
      "最新消息內文最新消息內文最新消息內文最新消息內文最新消息內文最新消息內文最新消息內文最新消息內文最新消息內文最新消息內文",
    type: "event",
    date: "2024-11-24",
  },
  {
    id: 5,
    title: "最新消息內文最新消息內文最新消息內文",
    type: "news",
    date: "2024-11-22",
  },
  {
    id: 6,
    title: "最新消息內文最新消息內文",
    type: "announcement",
    date: "2024-11-20",
  },
  {
    id: 7,
    title: "最新消息內文",
    type: "event",
    date: "2024-11-18",
  },
  {
    id: 8,
    title: "最新消息內文最新消息內文最新消息內文",
    type: "news",
    date: "2024-11-16",
  },
  {
    id: 9,
    title: "最新消息內文最新消息內文最新消息內文最新消息內文最新消息內文",
    type: "announcement",
    date: "2024-11-14",
  },
  {
    id: 10,
    title: "最新消息內文最新消息內文",
    type: "event",
    date: "2024-11-12",
  },
  {
    id: 11,
    title: "最新消息內文最新消息內文最新消息內文",
    type: "news",
    date: "2024-11-10",
  },
  {
    id: 12,
    title: "最新消息內文最新消息內文最新消息內文",
    type: "announcement",
    date: "2024-11-08",
  },
  {
    id: 13,
    title: "最新消息內文",
    type: "event",
    date: "2024-11-06",
  },
  {
    id: 14,
    title: "最新消息內文",
    type: "news",
    date: "2024-11-04",
  },
  {
    id: 15,
    title: "最新消息內文最新消息內文最新消息內文",
    type: "announcement",
    date: "2024-11-02",
  },
  {
    id: 16,
    title: "最新消息內文最新消息內文最新消息內文",
    type: "event",
    date: "2024-11-01",
  },
  {
    id: 17,
    title: "最新消息內文最新消息內文最新消息內文最新消息內文",
    type: "news",
    date: "2024-10-31",
  },
  {
    id: 18,
    title: "最新消息內文",
    type: "announcement",
    date: "2024-10-30",
  },
  {
    id: 19,
    title: "最新消息內文",
    type: "event",
    date: "2024-10-30",
  },
  {
    id: 20,
    title: "最新消息內文",
    type: "news",
    date: "2024-10-30",
  },
  {
    id: 21,
    title: "最新消息內文最新消息內文最新消息內文最新消息內文",
    type: "announcement",
    date: "2024-10-29",
  },
  {
    id: 22,
    title: "最新消息內文最新消息內文最新消息內文最新消息內文",
    type: "event",
    date: "2024-10-24",
  },
  {
    id: 23,
    title: "最新消息內文最新消息內文",
    type: "news",
    date: "2024-10-22",
  },
  {
    id: 24,
    title: "最新消息內文",
    type: "announcement",
    date: "2024-10-20",
  },
  {
    id: 25,
    title:
      "最新消息內文最新消息內文最新消息內文最新消息內文最新消息內文最新消息內文最新消息內文",
    type: "event",
    date: "2024-10-18",
  },
  {
    id: 26,
    title: "最新消息內文",
    type: "news",
    date: "2024-10-16",
  },
  {
    id: 27,
    title: "最新消息內文",
    type: "announcement",
    date: "2024-10-14",
  },
  {
    id: 28,
    title: "最新消息內文",
    type: "event",
    date: "2024-10-12",
  },
];
